#include <systemd/sd-event.h>

int const LIBSYSTEMD_SYS__SD_EVENT_OFF = SD_EVENT_OFF;
int const LIBSYSTEMD_SYS__SD_EVENT_ON = SD_EVENT_ON;
int const LIBSYSTEMD_SYS__SD_EVENT_ONESHOT = SD_EVENT_ONESHOT;

int const LIBSYSTEMD_SYS__SD_EVENT_INITIAL = SD_EVENT_INITIAL;
int const LIBSYSTEMD_SYS__SD_EVENT_ARMED = SD_EVENT_ARMED;
int const LIBSYSTEMD_SYS__SD_EVENT_PENDING = SD_EVENT_PENDING;
int const LIBSYSTEMD_SYS__SD_EVENT_RUNNING = SD_EVENT_RUNNING;
int const LIBSYSTEMD_SYS__SD_EVENT_EXITING = SD_EVENT_EXITING;
int const LIBSYSTEMD_SYS__SD_EVENT_FINISHED = SD_EVENT_FINISHED;

int const LIBSYSTEMD_SYS__SD_EVENT_PRIORITY_IMPORTANT = SD_EVENT_PRIORITY_IMPORTANT;
int const LIBSYSTEMD_SYS__SD_EVENT_PRIORITY_NORMAL = SD_EVENT_PRIORITY_NORMAL;
int const LIBSYSTEMD_SYS__SD_EVENT_PRIORITY_IDLE = SD_EVENT_PRIORITY_IDLE;


// int const LIBSYSTEMD_SYS__SD_JOURNAL_LOCAL_ONLY = SD_JOURNAL_LOCAL_ONLY;
// int const LIBSYSTEMD_SYS__SD_JOURNAL_RUNTIME_ONLY = SD_JOURNAL_RUNTIME_ONLY;
// int const LIBSYSTEMD_SYS__SD_JOURNAL_SYSTEM = SD_JOURNAL_SYSTEM;
// int const LIBSYSTEMD_SYS__SD_JOURNAL_CURRENT_USER = SD_JOURNAL_CURRENT_USER;
//
// int const LIBSYSTEMD_SYS__SD_JOURNAL_NOP = SD_JOURNAL_NOP;
// int const LIBSYSTEMD_SYS__SD_JOURNAL_APPEND = SD_JOURNAL_APPEND;
// int const LIBSYSTEMD_SYS__SD_JOURNAL_INVALIDATE = SD_JOURNAL_INVALIDATE;
